ARG SWIFT_VERSION=6.2
ARG SWIFT_DISTRIBUTION_TAG=rhel-ubi9
FROM swift:${SWIFT_VERSION}-${SWIFT_DISTRIBUTION_TAG}
ARG EXTRA_PACKAGES
RUN dnf -y install systemd-devel ${EXTRA_PACKAGES} && dnf clean all
