ARG SWIFT_VERSION=6.2
ARG SWIFT_DISTRIBUTION_TAG=amazonlinux2
FROM swift:${SWIFT_VERSION}-${SWIFT_DISTRIBUTION_TAG}
ARG EXTRA_PACKAGES
RUN yum -y install systemd-devel ${EXTRA_PACKAGES} && yum clean all
