ARG SWIFT_VERSION=6.2
ARG SWIFT_DISTRIBUTION_TAG=jammy
FROM swift:${SWIFT_VERSION}-${SWIFT_DISTRIBUTION_TAG}
ARG EXTRA_PACKAGES
RUN apt update && apt -y install libsystemd-dev ${EXTRA_PACKAGES} && apt -y clean
