ARG SWIFT_IMAGE_VERSION=6.2.4
ARG SWIFT_DISTRIBUTION_TAG=jammy
FROM swift:${SWIFT_IMAGE_VERSION}-${SWIFT_DISTRIBUTION_TAG}
ARG EXTRA_PACKAGES
RUN apt update && apt -y install libsystemd-dev ${EXTRA_PACKAGES} && apt -y clean
