name: Build SDK for a given Swift version, distribution, and target architecture
description: This performs all the actions needed to generate a cross-compilation SDK.
inputs:
  swift-version:
    description: The version of Swift to use (.e.g., 6.0.3).
    required: true
  distribution:
    description: The name of the distribution to use for this SDK (e.g., ubuntu-jammy, rhel-ubi9).
    required: true
  target-arch:
    description: The architecture to generate the SDK for (.e.g, x86_64, aarch64, armv7).
    required: true
runs:
  using: "composite"
  steps:
  - name: Build SDK
    shell: bash
    run: |
      ./build-sdk.sh ${{ inputs.swift-version }} ${{ inputs.distribution }} ${{ inputs.target-arch }}
  - name: Test SDK with test-project
    shell: bash
    run: |
      ./test-sdk.sh ${{ inputs.swift-version }} ${{ inputs.distribution }} ${{ inputs.target-arch }} --build-tests
      cp test-project/.build/debug/hello-world artifacts
      cp test-project/.build/debug/*.xctest artifacts
  - name: Test SDK with test-project (static)
    shell: bash
    run: |
      ./test-sdk.sh ${{ inputs.swift-version }} ${{ inputs.distribution }} ${{ inputs.target-arch }} --static-swift-stdlib
      cp test-project/.build/debug/hello-world artifacts/hello-world-static
  - uses: actions/upload-artifact@v4
    name: Publish SDK
    with:
      name: artifacts-${{ inputs.swift-version }}-${{ inputs.distribution }}-${{ inputs.target-arch }}
      path: |
        artifacts/*
